/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_bsdb_io_Native_Uring */

#ifndef _Included_ai_bsdb_io_Native_Uring
#define _Included_ai_bsdb_io_Native_Uring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ai_bsdb_io_Native_00024Uring_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    initUring
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_initUring
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    exitUring
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ai_bsdb_io_Native_00024Uring_exitUring
  (JNIEnv *, jobject);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    registerBuffers
 * Signature: ([J[J)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_registerBuffers
  (JNIEnv *, jobject, jlongArray, jlongArray);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    unregisterBuffers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_unregisterBuffers
  (JNIEnv *, jobject);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    registerFiles
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_registerFiles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    unregisterFiles
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_unregisterFiles
  (JNIEnv *, jobject);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    availableSQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_availableSQ
  (JNIEnv *, jobject);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareRead
 * Signature: (JJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareRead
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareReadM
 * Signature: ([JJI[J[I[JII)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareReadM
  (JNIEnv *, jobject, jlongArray, jlong, jint, jlongArray, jintArray, jlongArray, jint, jint);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareReads
 * Signature: (JJI[J[IJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareReads
  (JNIEnv *, jobject, jlong, jlong, jint, jlongArray, jintArray, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareReadFixed
 * Signature: (JJIJIJI)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareReadFixed
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareWrite
 * Signature: (JJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareWrite
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareWrites
 * Signature: (JJI[J[IJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareWrites
  (JNIEnv *, jobject, jlong, jlong, jint, jlongArray, jintArray, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareWriteFixed
 * Signature: (JJIJIJI)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareWriteFixed
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    prepareFsync
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_prepareFsync
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    submit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_submit
  (JNIEnv *, jobject);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    submitAndWait
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_submitAndWait
  (JNIEnv *, jobject, jint);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    waitCQEntryTimeout
 * Signature: ([J[JJ)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_waitCQEntryTimeout
  (JNIEnv *, jobject, jlongArray, jlongArray, jlong);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    waitCQEntries
 * Signature: ([J[JI)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_waitCQEntries
  (JNIEnv *, jobject, jlongArray, jlongArray, jint);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    peekCQEntries
 * Signature: ([J[JI)I
 */
JNIEXPORT jint JNICALL Java_ai_bsdb_io_Native_00024Uring_peekCQEntries
  (JNIEnv *, jobject, jlongArray, jlongArray, jint);

/*
 * Class:     ai_bsdb_io_Native_Uring
 * Method:    advanceCQ
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ai_bsdb_io_Native_00024Uring_advanceCQ
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
