/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_bsdb_io_Native */

#ifndef _Included_tech_bsdb_io_Native
#define _Included_tech_bsdb_io_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_bsdb_io_Native
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_tech_bsdb_io_Native_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     tech_bsdb_io_Native
 * Method:    allocateAligned
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_tech_bsdb_io_Native_allocateAligned
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     tech_bsdb_io_Native
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tech_bsdb_io_Native_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tech_bsdb_io_Native
 * Method:    pread
 * Signature: (IJJI)J
 */
JNIEXPORT jlong JNICALL Java_tech_bsdb_io_Native_pread
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

/*
 * Class:     tech_bsdb_io_Native
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tech_bsdb_io_Native_close
  (JNIEnv *, jclass, jint);


JNIEXPORT jlong JNICALL Java_tech_bsdb_io_Native_loadHash
  (JNIEnv *, jclass, jstring);

JNIEXPORT jlong JNICALL Java_tech_bsdb_io_Native_getHash
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
